var GAME_LEVELS = [
  [" % o                                    ",
   "                                       ",
   "xxxx     o     o      o o               ",
   "!!!!xx                                 ",
   "!!!!!!!xxx   xx  x  xxx    		   ",               					            
   "       		 x                         ",                                             			                                                            			
   "            x             x            ",                                                                                      		
   "           x                  x		   ",           												
   "                o       x	   ",                                              	
   "         			      	xx!!!!!!!!  ",
   " o          xx                ",
   "       o  o   o   x                    ",
   " @              x              		   ",
   "xxx!!!xx!!x!!xx                        ",
   "                                       "],
  ["                                                                                                                  ",                               
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                    o                                                                             ",
   "                                                                                                                  ",
   "                                   o  x                                                                           ",
   "     o                         x  x   o                                                                           ",
   "     %           !!                               x=            x                                                  ",
   "    xxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxx      xxxxxxxxxxxxx         xxxxx xxxxxxxx                           ",                                          
   "                                                                                       o                          ",
   "                                                                                                                  ",
   "                                                                                       xxx                        ",
   "                                                                                                                  ",
   "                                                      o                              xxxxxx                       ",
   "                                                                                   x                              ",
   "x	   o                 o          o                                            x                                ",
   "x                                               xxx                   o         x                                  ",
   "x @                                           x                              x                                    ",
   "xxxxxxxxxxx   xxxx  xx   x  xxxx         xxxx       xxxxxxx   x!!!!xxxxxxxxx!!!!!!xxxxxxxxxxxxxxx!!xxxx!!xxxxx x  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                                 ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ", 
   "                                                                            x                                     ",
   "                                                                    xxxx                                          ",
   "                                                                                 x                                ",
   "                                                                                                                  ",
   "                                                               x            x                                     ",
   "                                                                                                                  ",
   "                                                                       x        !!!!!!!                           ", 
   "                                                                                                                  ",
   "                                                          x  !!!!!!       x                                       ",
   "                                       x                                                               o          ",
   "                                 x     !                                 !!!!xxxx                                 ",
   "                                 x     o                                                     o         xx         ",
   "                                 x     o                                             xxxxx                        ",
   "                                 x     o                                                     x  !!!!              ",
   "                                 x     !                                                                  xxxx    ",
   "                                 x  %  x    x                                   o    x    o                       ",
   "                                 xxxxxxxxxxxxxxx!!xxxxxxx                                                         ",
   "                                                                               xxxxx              xxxx            ",
   "                                                        xxxx                        !!!!!!!xxxx                   ",
   "                                                                                                                  ",
   "                                                         oo    xxxxx!!!!!!!xxxxx                                  ",
   "                                                                                                                  ",
   "  x                xxx                        o         xxxx                                                      ",
   "  x               xxxxx                                                                                           ",
   "  x               oxxxo                     xxxx                                                                  ",
   "  x                xxx                            xxx                                                             ",
   "  x      @          x                                                        x=             =               =x    ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!x xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     "]
   "                                                          
   "                                                                                                                  "],
  ["                                                                                                                  ",                                                      
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                            o      o                              ",
   "                                                                           x                                      ",
   "                                                                           x%                                     ",
   "                                                                           xxxxxxxxx                              ",
   "                                                                                                                  ",
   "                                                                                          o                       ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                        xxxxxxxx     o            ",
   "                                                                                             o                    ",
   "                                                                                                    =x            ",
   "         x                                                                               xxxxxxxxxxxxx            ",
   "         v                                                             xxxxxx                                     ",
   "                                                               o                                                  ",
   "                                                                                                                  ",
   "                                                             xxxxx                                                ",
   "                              o o o                                                                               ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "  xxxxxx   xxxxxxx                      xxxxxxxxxx   xxxx!!!!!!!!!!!!!!!!!                                        ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "        !!! !!!!!!!!!!!!!!!xxxxxxxxxxxx!!!!!!!!                                                                   ",
   "                                                                                                                  "],
  ["                                                                                                                         ",
 "   xxx    xxx                                                                                                               ",
 "   xxx    xxx                                                                                                               ",
  "  xxx    xxx                                                           xxx            xxx                                  ",
  "     xxx                                                               xxx            xxx                                  ",
  "     xxx                                                               xxx            xxx                                  ",
  "     xxx              xxxxxxxx         xxx       xxx                   xxx    xxx     xxx        xxxx       xxxxxxxxxxx    ",
  "     xxx          xxx         xxx      xxx       xxx                   xxx    xxx     xxx        xxxx       xxx     xxx    ",
  "     xxx          xxx         xxx      xxx       xxx                   xxx    xxx     xxx        xxxx       xxx     xxx    ",
  "     xxx          xxx         xxx      xxx       xxx                   xxx    xxx     xxx        xxxx       xxx     xxx    ",
  "     xxx          xxx         xxx      xxx       xxx                   xxx    xxx     xxx        xxxx       xxx     xxx    ",
  "     xxx          xxx         xxx      xxx       xxx                   xxx    xxx     xxx        xxxx       xxx     xxx    ",
  "     xxx             xxxxxxxxx            xxxxxxx                        xxxxx  xxxxx            xxxx       xxx     xxx    ",
  "                                                                                                                           "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
